// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqkumhexmqnkvagaswzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa3VtaGV4bXFua3ZhZ2Fzd3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODc3NTgsImV4cCI6MjA2ODE2Mzc1OH0.r2mMrA5y3XU5Y_afdP7H8lHZGBd-up2eIK01qIv1qEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});